### ISSUE TITLE
🚀 Feature: Add rss.xml feed link 

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/dot-com#160]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/joshuakgoldberg-dot-com-next/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

TIL it's common + recommended for blogs to include a `<link>` to their RSS feed in blog page `<head>`s.

```xml
<link
  href="/feed.xml"
  rel="alternate"
  title="RSS Feed"
  type="application/rss+xml"
/>
```

### Additional Info

Reported by @stefanjudis on Twitter: https://twitter.com/stefanjudis/status/1747258268052066306. Thanks Stefan!

**Comment by stefanjudis** [comment]
Yay! 🚀
