### ISSUE TITLE
UI-Fixes

### ISSUE THREAD

**Issue by justankiit** [JoshuaKGoldberg/dot-com#4]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/joshuakgoldberg-dot-com-next/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

The Font Weight of the About section should be Bolder to an extent , Because for now We have to see the page from more nearly and it is looking more light.
![about](https://user-images.githubusercontent.com/111564362/230719393-941ee2d5-2cd4-4827-a5b4-7859ceaaf0d8.jpg)

**Comment by JoshuaKGoldberg** [comment]
Thanks @kumarankit999 but this site isn't ready for issues or IRs yet. I'm still working on it 😄

**Comment by justankiit** [comment]
OK, No problem at all.I have seen some issues and raised here.
